version: "3.8"
services:
  app:
    image: "fx-deals-importer-app"
    build:
      context: .
    container_name: fx-deals-importer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${APP_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_AUTH_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_AUTH_PASSWORD}
    networks:
      - app-network
  db:
    image: "postgres:latest"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_AUTH_USERNAME}
      - POSTGRES_PASSWORD=${DB_AUTH_PASSWORD}
      - POSTGRES_DB=${DEFAULT_DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  pg-data:

networks:
  app-network: {}